sshahine/JFoenix

src/com/jfoenix/controls/JFXDialog.java

Animation needs to be re-instantiated for each call of the show() method.

Fixed defualt show method

---

README.md
make/build.sh
make/run-demo.sh

Allows better cross-platform compatibility. Build instructions are also updated in readme. Steps to build using ant on Linux remain same as on Windows, albeit with the shell scripts, not the batch files.

Create shell scripts for ant build

---

src/com/jfoenix/concurrency/JFXUtilities.java

As described in Java Concurrency In Practice, pp. 92ff.,
InterruptedException should either be propagated to the caller
or the interruption status should be restored.
See [the original text](https://cdn.rawgit.com/HackathonHackers/programming-ebooks/master/Java/Java%20Concurrency%20in%20Practice.pdf#page=114).
(Go to pages 114f.. of the PDF if it does not scroll automatically, it's pages 92ff. in the original book)

Restore interruption status on InterruptedException

---

src/com/jfoenix/controls/JFXSnackbar.java

Trying to refresh the container before registering it caused a NullPointerException.
This little modification should solve it.

Should solve NullPointerException in JFXSnackbar constructor

---

README.md

I noticed that some features are not available inside the old version 1.0.0, e.g., JFXTreeView. As a result, it's better to notify the readers that the newest version when they are using Gradle.

Update JFoenix Version in Gradle Configurations

---

jfoenix/src/main/java/com/jfoenix/controls/JFXNodesList.java

`ArrayList` as argument type was a needless restriction on the type the caller can pass. 
This is a backwards compatible change.

refactor: JfxNodesList accepts any Collection as arguments, not only ArrayList

---

jfoenix/src/main/java/com/jfoenix/skins/JFXTimePickerContent.java

Java get default locale for JVM from windows preference.
My default locale for JVM was korean and It thorws an exception even I
set LocalTimeStringConverter to English.
We can set the locale for jvm in several ways.
(http://www.oracle.com/technetwork/articles/javase/locale-140624.html#using)
But the best way is change some code.
I use DateTimeFormatter not localTiemStringConverter.

fix the timePickerContest.updateValue DateTimeParseException

---

jfoenix/src/main/java/com/jfoenix/validation/base/ValidatorBase.java

Adding message String to constructor allows you to short validator creation:
Before:
```java
RequiredFieldValidator val = new RequiredFieldValidator();
val.setMessage("Custom message");
myInput.getValidators().add(val);
```
After:
```java
myInput.getValidators().add(new RequiredFieldValidator("My custom message"));
```

Set custom message to Validator constructor

---

jfoenix/src/main/java/com/jfoenix/controls/JFXToggleButton.java
jfoenix/src/main/java/com/jfoenix/skins/JFXToggleButtonSkin.java

There is no way to decide the size of JFXToggleButton, because the values of the size are unmodifiable.
This pull request aims at adding an easy way to resize the JFXToggleButton.

Add css 'jfx-size' property to resize toggle button

---

LICENSE
README.md
demo/src/main/java/demos/MainDemo.java

Running the demo on a mac book pro 13' opens a window that exceeds the limits of the screen. Additionally, the window is unable to be resized because of the fixed minimum dimensions. As you can see below.
I removed the fixed minimum dimensions, so that the resulting smaller window can be maximized to the individual's screen. 
Finally, I updated the README to include the specific path and file names to the JAR generated via Gradle.

Fixed demo sizing issue & updated readme

---

jfoenix/src/main/java/com/jfoenix/controls/JFXButton.java
jfoenix/src/main/java/com/jfoenix/skins/JFXButtonSkin.java

Added the css property -jfx-disable-visual-focus to JFXButton. This provides the ability to disable the rippler from showing when the JFXButton has focus. The value is defaulted to false.

Displaying focus in JFXButton should be optional

---

jfoenix/src/main/java/com/jfoenix/controls/JFXRadioButton.java
jfoenix/src/main/java/com/jfoenix/controls/JFXToggleButton.java
jfoenix/src/main/java/com/jfoenix/skins/JFXRadioButtonSkin.java
jfoenix/src/main/java/com/jfoenix/skins/JFXToggleButtonSkin.java

This is issue is essentially the same as #471 but instead applied to JFXRadioButton and JFXToggleButton.

Displaying visual focus should be optional for JFXRadioButton and JFXToggleButton

---

README.md

It makes more sense to me if the link goes to the github page instead of the itch.io page. I created LoLPing to learn about JavaFX and JFoenix, so I'd love to have people seeing my code and suggesting me how to improve it, because I am sure there's a lot to improve.

Make LoLPing link go to the github page.

---

demo/src/main/java/demos/MainDemo.java
jfoenix/src/main/java/com/jfoenix/controls/JFXDecorator.java

This improves the way the user sets the JFXDecorator's text. We call the text "title" and automatically bind it to the `primaryStage`'s title by default. Unbinding the two is easily done by calling `setTitle()`.

This improves the way the user sets the JFXDecorator's text.

---

demo/src/main/java/demos/gui/sidemenu/SideMenuController.java
demo/src/main/java/demos/gui/uicomponents/NodesListController.java
demo/src/main/resources/fxml/SideMenu.fxml
demo/src/main/resources/fxml/ui/NodesList.fxml
jfoenix/src/main/java/com/jfoenix/controls/JFXNodesList.java

Allows the user to specify children for a JFXNodesList in FXML. See #613.
I wonder if the page in the main demo might be better named "Speed Dial", as per the Material Design Guidelines, (https://material.io/guidelines/components/buttons-floating-action-button.html#transitions-figure-caption-6).
What do you think?

Add FXML Support for JFXNodesList

---

jfoenix/src/main/java/com/jfoenix/transitions/hamburger/HamburgerBasicCloseTransition.java
jfoenix/src/main/java/com/jfoenix/transitions/hamburger/HamburgerSlideCloseTransition.java

Hello, I just updated the design of the close icon in the hamburger transitions.
Old version :
Updated version :
Current material design version :
Let me know if there is any problem 😃

fix close button design

---

jfoenix/src/main/java/com/jfoenix/controls/JFXMasonryPane.java

I have implemented the fix discussed on #833.
JFXMasonryPane `animationMap` attribute is now correctly cleared when childs are removed.

fixed #833 Memory leaks using JFXMasonryPane

---

jfoenix/src/main/java/com/jfoenix/controls/JFXTimePicker.java

I believe this is the right format. It would also allow for Kotlin interoperability (e.g.: `timePicker.is24HourView = true`).

`JFXTimePicker.setIs24HourView` to `JFXTimePicker.set24HourView`

---

demo/src/main/java/demos/components/AnimationTemplateDemo.java
jfoenix/src/main/java/com/jfoenix/transitions/template/ConditionalInterpolator.java
jfoenix/src/main/java/com/jfoenix/transitions/template/JFXAnimationTemplate.java
jfoenix/src/main/java/com/jfoenix/transitions/template/JFXAnimationTemplateAction.java
jfoenix/src/main/java/com/jfoenix/transitions/template/JFXAnimationTemplateConfig.java
jfoenix/src/main/java/com/jfoenix/transitions/template/JFXAnimationTemplates.java

This should be the last fixes for now :wink: 
I fixed the the behaviour of the "animateWhen" method.
The problem was that I check the "animateWhen" condition only at build time of the JFXAnimationTemplate so it was more a "buildWhen" conditon :wink: 
For this purpose the ConditionalInterpolator was added which intercepts a Interpolator instance with a condition and can be used with any implementation which uses Interpolators for it's key values.
Furthermore a "executions" method was add where a number of executions for an action can be defined.
This can be used for e.g. init behaviour for an animation.
Greetings

Final JFXTemplateAnimation fixes.

---

jfoenix/src/main/java/com/jfoenix/controls/JFXTimePicker.java

Using the default Local instead hard coded to Locale.ENGLISH.
If the client has set default Locale to UK, it will show AM/PM in TimePicker, because the Locale is hard coded to ENGLISH.

Use the default Locale in TimePicker StringConverter

---

jfoenix/src/main/java/com/jfoenix/skins/JFXDatePickerContent.java

Take the last character of the Chinese weekday names instead of the third character #893

Fix Chinese environment week display incorrectly again

---

jfoenix/src/main/java/com/jfoenix/controls/JFXDialog.java

Without the removal from the container, this will cause an error when opening a dialog that hasn't been closed already

Prevent error when reopening non-closed JFXDialog

---

jfoenix/src/main/java/com/jfoenix/skins/JFXDatePickerContent.java

Hi,
regarding the issue #921 I tried a little bit around with the datepicker. 
I'm not sure if this is the solution for the issue but I think it is actual an issue :wink:
If a december date gets picked in the datepicker and afterwards the year is changed and you slide to the next month which is the next years january the wrong year is selected:
The selectedYearMonth property of the datepicker contains always the right year so I set this year to the offset of dateCell.
Fixed:
Greetings

Fix for wrong datepicker year jump

---

jfoenix/src/main/java/com/jfoenix/controls/JFXDecorator.java

My best guess is that someone tried to copy and reuse `setGraphic`'s signature, but forgot to remove it's `Node`, parameter. This just gets rid of that.

Fix JFXDecorator's getGraphic

---

jfoenix/src/main/java/com/jfoenix/validation/RegexValidator.java

Matcher doesn't like nulls. If the text is null, we'll treat it like an empty string.

Null check for RegExValidator

---

jfoenix/src/main/java/com/jfoenix/validation/base/ValidatorBase.java

In PR #1013, I did this same fix, but on an old version of `ValidatorBase`. This applies that same fix to the most recent version, instead.
While I was at it, I also added documentation for almost everything in `ValidatorBase`. Feel free to check my work, as I'm not the original author of the class—what I wrote is based on assumptions.

Support tooltips for non-controls in ValidatorBase and add documentation

---

jfoenix/build.gradle

Starting with Java 9 you need to write without 1.

fixed OSGI manifest for Java9+

---

jfoenix/src/main/java/com/jfoenix/skins/JFXTabPaneSkin.java

support  SELECTED_TAB policy  #75 
@jfoenixadmin 
Just add the following configuration：
`tabPane.setTabClosingPolicy(TabPane.TabClosingPolicy.SELECTED_TAB);`

Fix TabPane close button display problem

---

jfoenix/src/main/java/com/jfoenix/transitions/JFXKeyFrame.java
jfoenix/src/main/java/com/jfoenix/transitions/JFXKeyValue.java

`JFXKeyFrame` used instead of `JFXKeyFrame<?>`. Also simplified a return statement. If this is unintended I will go through the entire project and fix similar problems with generics, and add the commits before merge.

Fix raw use of parameterized class
