demo/demos/gui/uicomponents/IconsController.java
demo/resources/css/jfoenix-components.css
demo/resources/css/jfoenix-main-demo.css
demo/resources/fxml/ui/Icons.fxml
src/com/jfoenix/controls/JFXBadge.java
src/com/jfoenix/controls/JFXRippler.java
src/com/jfoenix/converters/BadgeMaskTypeConverter.java
src/com/jfoenix/converters/RipplerMaskTypeConverter.java

Add Badge support to JFoenix
https://www.getmdl.io/components/index.html#badges-section

Added Material Design Badges

---

demo/demos/gui/uicomponents/PopupController.java
demo/resources/css/jfoenix-components.css
demo/resources/css/jfoenix-main-demo.css
demo/resources/fxml/ui/Popup.fxml
src/com/jfoenix/controls/JFXSnackbar.java

https://www.google.com/design/spec/components/snackbars-toasts.html
http://www.getmdl.io/components/#snackbar-section

Addition of Material Design Snackbar and Toast

---

README.md
circle.yml

CircleCI support

---

build.gradle
gradle/publishing.gradle

Apply SCM commit hash to JAR manifest

---

src/com/jfoenix/skins/JFXTimePickerContent.java

Description
It crashes in non English default locale (test in French) in the updateValue.
Solution
Specify the Locale in the LocalTimeStringConverter constructor

FIX[#98] JFXTimePicker error when Locale!=ENGLISH

---

demo/demos/gui/uicomponents/TreeTableViewController.java
demo/resources/fxml/ui/TreeTableView.fxml

Demonstrate dynamically adding/removing rows with JFXTreeTableView. Adding and removing while filter is selected does not make a permanent change to backing items because the filtered view is temporary view.

Enhanced JFXTreeTable demo to show table adds and removes

---

src/com/jfoenix/controls/cells/editors/DoubleTextFieldEditorBuilder.java
src/com/jfoenix/validation/DoubleValidator.java
src/com/jfoenix/validation/NumberValidator.java

Now we can edit JFXTreeTableColumn of Double type, added simple validator for it and a little typo fix.

add DoubleTextFieldEditor and DoubleValidator

---

src/com/jfoenix/skins/JFXTabPaneSkin.java

Now the SECONDARY button click would open context menu:

Fixed #231 JFXTabPane no context menu

---

demo/src/main/resources/css/jfoenix-components.css
demo/src/main/resources/css/jfoenix-main-demo.css
jfoenix/src/main/resources/css/jfoenix-design.css
jfoenix/src/main/resources/css/jfoenix-fonts.css

Should I say something more? ;)

:art: CSS Reformat

---

jfoenix/src/main/java/com/jfoenix/controls/JFXTimePicker.java
jfoenix/src/main/java/com/jfoenix/skins/JFXTimePickerContent.java

Added a 24-hour UI selection for JFXTimePicker.

24-hour UI selection for JFXTimePicker

---

README.md

https://github.com/skmedix/JFoenix/blob/381baa295fb9d95f138afc2c40d052f9db36fd4e/README.md
Btw.. Download files aren't the latest one
Second btw.. Having Travis on this repo would be nice

readme: few improvements

---

demo/src/main/java/demos/components/TreeViewDemo.java

This line is [actually breaking](https://circleci.com/gh/jfoenixadmin/JFoenix/230) building process

Removed unused import

---

jfoenix/src/main/java/com/jfoenix/controls/JFXDrawer.java

Removed some commented out code from JFXDrawer and updated the documentation on some of the methods.

JFXDrawer: Code cleanup and documentation 

---

demo/src/main/java/demos/MainDemo.java
demo/src/main/resources/css/jfoenix-main-demo.css
jfoenix/src/main/java/com/jfoenix/controls/JFXDecorator.java

Added a Title to the JFXDecorator. This title can be set by calling setTitle(String) function on the JFXDecorator. Created a jfx-decorator-label css for styling. Please feel free to change that styling. Also this is my 1st contribution to any open source project. Please provide feedback

Added a Title to the JFXDecorator (see Main Demo)

---

README.md

VersionEye is gonna be shut down by the end of the month.
https://blog.versioneye.com/2017/10/19/versioneye-sunset-process/

Removed VersionEye badge

---

demo/src/main/resources/css/jfoenix-main-demo.css

Change font anti-aliasing.

---

README.md

I've done some work in the Wiki, and I thought I'd make it crystal clear for the less experienced how to get the demo running.

Add steps to run demo for the noobs

---

jfoenix/src/main/java/com/jfoenix/validation/RequiredFieldValidator.java

With this you can validate TimePicker, DatePicker or any control that extends ComboBoxBase.

Changed RequiredValidator to allow any ComboBoxBase

---

README.md

Update versions and include java 9

Update example gradle dependencies in README

---

README.md

I made some new wiki pages and linked them to each component. I also added a title to each .gif to make it easier to find.

Updated README to link to wiki pages

---

README.md

I had to remove LoLPing's code from github, so the link is broken. JMarkPad is another project of mine that uses JFoenix.

Replace LoLPing 2 with JMarkPad

---

jfoenix/src/main/java/com/jfoenix/validation/NumberValidator.java

same functionality as listed in #664

#664 code refactor

---

jfoenix/src/main/java/com/jfoenix/skins/JFXColorPickerSkin.java

Allow null color in JFXColorPicker

---

jfoenix/src/main/java/com/jfoenix/validation/RegexValidator.java

PR for #796.
Thank you for maintaining such a nice library!

[#796]: Created RegexValidator for TextInputControl.

---

README.md

Hi JFoenix team,
I made a project which uses peer to peer paradigm to communicate messages among different hosts. Users can choose a directory to share and files can be shared. I've implemented the material design using JFoenix.
Link: https://github.com/rohan23chhabra/p2p

Added a project which uses JFoenix library.

---

README.md

Another project using JFoenix... Nice to see that the list become longer and longer over the years. ;)
I'm actively working on OwlPlug during my free time. It's a tool to manage Audio Plugins setup. UI/UX still perfectible but i think it's a great showcase of how complete and powerfull JFoenix is.
Regards,

Add OwlPlug in JFoenix projects

---

jfoenix/src/main/resources/css/controls/jfx-color-picker.css

Add min/pref height to color picker

---

README.md

Added MS Paint IDE to the projects list :)
I've been using JFoenix for a while with the project to produce a slick UI for the IDE, since it's easy to make things that look good with it, and I love Material Design.

Added MS Paint IDE to JFoenix projects

---

jfoenix/src/main/java/com/jfoenix/controls/JFXChipView.java
jfoenix/src/main/java/com/jfoenix/skins/JFXChipViewSkin.java

Hi ! I've added a simple property on JFXChipView to fill the associated TextArea promptText. 🙂 
You can use it like this: `chipView.setPromptText("Some placeholder");`

Added promptText property to JFXChipView

---

README.md

I've been using JFoenix since 1.0.0 to my project. without JFoenix, Actlist won't be exists :)

Add Actlist in JFoenix projects

---

jfoenix/src/main/java/com/jfoenix/controls/JFXDrawer.java
jfoenix/src/main/java/com/jfoenix/controls/JFXTreeTableView.java

replace toArray(new T[size]) with toArray(new T[0]) for better performance
https://shipilev.net/blog/2016/arrays-wisdom-ancients/#_conclusion

Optimize toArray

---

jfoenix/src/main/java/com/jfoenix/skins/JFXPopupSkin.java

After manually hiding and reopening, the same error appears as in #778
Used the same fix from the initialization

Fixed error with re-opening a popup containing a ScrollPane

---

demo/build.gradle
demo/src/main/java/demos/components/TextAreaDemo.java
demo/src/main/java/demos/components/TextFieldDemo.java
demo/src/main/java/demos/components/ToggleButtonDemo.java
demo/src/main/java/demos/gui/uicomponents/TextFieldController.java
demo/src/main/resources/fxml/ui/Combobox.fxml
demo/src/main/resources/fxml/ui/Icons.fxml
demo/src/main/resources/fxml/ui/NodesList.fxml
demo/src/main/resources/fxml/ui/TextField.fxml
demo/src/main/resources/fxml/ui/ToggleButton.fxml
demo/src/main/resources/fxml/ui/popup/DemoPopup.fxml
demo/src/main/resources/fxml/ui/popup/MainPopup.fxml

https://github.com/aalmiray/ikonli
_Java 8_
**Icons cheat sheet for 4.x:**
https://skmedix.github.io/ikonli-java-8/
**Icons cheat sheet for 4.x:**
https://skmedix.github.io/ikonli-java-8/cheat-sheet-fontawesome5.html
---
_Java 11_
**Usage for 11.x:**
http://aalmiray.github.io/ikonli/
**Icons cheat sheet for 11.x:**
http://aalmiray.github.io/ikonli/cheat-sheet-fontawesome5.html

 Changed icons lib to Ikonli FontAwesome 5

---

jfoenix/src/main/java/com/jfoenix/validation/StringLengthValidator.java

It will validate the length of a String.
The lenght of validation is given in the constructor of this class.

New Validation implemented for JFXTextField.

---

README.md

Add Sparkler to projects list

---

jfoenix/src/main/java/com/jfoenix/skins/JFXCheckBoxOldSkin.java
jfoenix/src/main/java/com/jfoenix/skins/JFXCheckBoxSkin.java

Max should be used to compute label width from pref and min width

Label width for checkboxes was computed wrongly

---

README.md

A pure picture viewer with some practical features.

New project using JFoenix

---

README.md

> Feel free to create a pull request for adding a link to your project in JFoenix github.
Let me know if you have any objections

Add Automation Boot to "Projects using JFoenix"

---

README.md

Add new project under the "projects using JFoenix" section.

Add: New project using JFoenix

---

README.md

* Adds [UniObfuscator](https://github.com/MJVL/UniObfuscator) to the project list

Add new project to project list

---

jfoenix/src/main/java/com/jfoenix/skins/JFXSpinnerSkin.java

fixed issue https://github.com/sshahine/JFoenix/issues/1181

fixed JFXSpinner's memory leak problem
